const GET_SHIFT_DETAILS = "GET_SHIFT_DETAILS";
const CANCEL_SHIFT = "CANCEL_SHIFT";
const BOOk_SHIFT = "BOOk_SHIFT";
const ERROR_SHIFT = "ERROR_SHIFT";
export { GET_SHIFT_DETAILS, CANCEL_SHIFT, BOOk_SHIFT, ERROR_SHIFT };
